name: rabbit_go
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fimber: ^0.7.0
  firebase_core: ^3.8.1
  cupertino_icons: ^1.0.8
  flutter_styled_toast: ^2.2.1
  firebase_crashlytics: ^4.2.0
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  stacked: ^3.4.4
  keyboard_actions: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:
  uses-material-design: true

  assets:
    - i18n/
    - assets/fonts/
    - assets/images/
    - assets/animations/

